# CREDIT CARD FRAUD DETECTION USING MACHINE LEARNING

Importing the dependencies

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [2]:
#loading the dataset in a pandas dataframe
credit_card_data = pd.read_csv('creditcard.csv')

In [3]:
#first 5 rows of the dataset
credit_card_data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
#last 5 rows of the dataset
credit_card_data.tail()

Time         V1         V2        V3        V4        V5  \
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[5 rows x 31 columns]

In [5]:
#dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [6]:
#checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [7]:
#before removing duplicates
credit_card_data.shape

(284807, 31)

In [8]:
#remove duplicates
credit_card_data.drop_duplicates(inplace=True)

In [9]:
#after removing duplicates
credit_card_data.shape

(283726, 31)

In [10]:
#distribution of legit transactions and fraudulent transactions
credit_card_data['Class'].value_counts()

0    283253
1       473
Name: Class, dtype: int64


This dataset is highly unbalanced 
0->normal transaction
1->fraudulent transaction

In [11]:
#separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [12]:
print(legit.shape)
print(fraud.shape)

(283253, 31)
(473, 31)


In [13]:
#statistiscal measures of data
legit.Amount.describe()

count    283253.000000
mean         88.413575
std         250.379023
min           0.000000
25%           5.670000
50%          22.000000
75%          77.460000
max       25691.160000
Name: Amount, dtype: float64

In [14]:
fraud.Amount.describe()

count     473.000000
mean      123.871860
std       260.211041
min         0.000000
25%         1.000000
50%         9.820000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [15]:
#compare the values of both transactions
credit_card_data.groupby('Class').mean()

Time        V1        V2        V3        V4        V5  \
Class                                                                   
0      94835.058093  0.013439 -0.009829  0.012853 -0.010440  0.006769   
1      80450.513742 -4.498280  3.405965 -6.729599  4.472591 -2.957197   

             V6        V7        V8        V9  ...       V20      V21  \
Class                                          ...                      
0      0.001251  0.010447 -0.002448  0.002613  ... -0.000489 -0.00115   
1     -1.432518 -5.175912  0.953255 -2.522124  ...  0.405043  0.46655   

            V22       V23       V24       V25       V26       V27       V28  \
Class                                                                         
0     -0.000160  0.000360  0.000393 -0.000301  0.000065  0.001409  0.000418   
1      0.086639 -0.096464 -0.106643  0.040615  0.050456  0.213774  0.078270   

           Amount  
Class              
0       88.413575  
1      123.871860  

[2 rows x 30 columns]

UnderSampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 473

In [16]:
legit_sample = legit.sample(n=473)

Concatenating two dataframes

In [17]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [18]:
new_dataset.head()

Time        V1        V2        V3        V4        V5        V6  \
78406    57511.0  1.264629 -0.212523  0.448531 -0.238811 -0.734429 -0.555945   
123408   76915.0  1.265271 -0.189142  0.172729  0.008196 -0.288775 -0.247775   
80458    58496.0 -0.769923  1.692726  1.040596  2.314980  0.771871  1.194325   
283015  171312.0 -0.189767  0.110463  0.943858 -1.858640  0.021766 -1.061964   
52707    45598.0 -0.405662  0.993962  1.075721  0.447830  0.106284 -0.515013   

              V7        V8        V9  ...       V21       V22       V23  \
78406  -0.444488  0.107403  0.436540  ... -0.125777 -0.470940  0.067463   
123408 -0.092912 -0.157616  0.647960  ... -0.138592 -0.151214 -0.203253   
80458   0.828797 -0.818222 -2.042708  ...  0.742252 -0.280914 -0.400340   
283015  0.362214 -0.256478 -1.222870  ...  0.300056  0.873610 -0.215426   
52707   1.065113 -0.200866 -0.485375  ...  0.085790  0.225689 -0.204817   

             V24       V25       V26       V27       V28  Amount  Class  
78406   0.015496  0.069551  0.913555 -0.086766 -0.008219    0.92      0  
123408 -0.319064  0.586308  1.156764 -0.065333 -0.000939   35.00      0  
80458  -1.004544  0.496995  0.351555  0.021805  0.031332   77.52      0  
283015  0.101118 -0.184154 -0.220611  0.140050  0.159459    3.95      0  
52707   0.028458  0.301745 -0.356328 -0.068766  0.000958   60.58      0  

[5 rows x 31 columns]

In [19]:
new_dataset.tail()

Time        V1        V2        V3        V4        V5        V6  \
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494   
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536   
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346   
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548   
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695   

              V7        V8        V9  ...       V21       V22       V23  \
279863 -0.882850  0.697211 -2.064945  ...  0.778584 -0.319189  0.639419   
280143 -1.413170  0.248525 -1.127396  ...  0.370612  0.028234 -0.145640   
280149 -2.234739  1.210158 -0.652250  ...  0.751826  0.834108  0.190944   
281144 -2.208002  1.058733 -1.632333  ...  0.583276 -0.269209 -0.456108   
281674  0.223050 -0.068384  0.577829  ... -0.164350 -0.295135 -0.072173   

             V24       V25       V26       V27       V28  Amount  Class  
279863 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00      1  
280143 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76      1  
280149  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89      1  
281144 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00      1  
281674 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53      1  

[5 rows x 31 columns]

In [20]:
new_dataset['Class'].value_counts()

0    473
1    473
Name: Class, dtype: int64

In [21]:
new_dataset.groupby('Class').mean()

Time        V1        V2        V3        V4        V5  \
Class                                                                   
0      97773.731501 -0.045089 -0.076944 -0.076474 -0.052720  0.031512   
1      80450.513742 -4.498280  3.405965 -6.729599  4.472591 -2.957197   

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...                       
0     -0.029818 -0.060825  0.112390  0.008471  ...  0.011952  0.006389   
1     -1.432518 -5.175912  0.953255 -2.522124  ...  0.405043  0.466550   

            V22       V23       V24       V25       V26       V27       V28  \
Class                                                                         
0      0.022968  0.011413  0.000465  0.025896 -0.000545  0.004937  0.008971   
1      0.086639 -0.096464 -0.106643  0.040615  0.050456  0.213774  0.078270   

           Amount  
Class              
0       88.100634  
1      123.871860  

[2 rows x 30 columns]

Splitting the data into targets and features

In [22]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [23]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
78406    57511.0  1.264629 -0.212523  0.448531 -0.238811 -0.734429 -0.555945   
123408   76915.0  1.265271 -0.189142  0.172729  0.008196 -0.288775 -0.247775   
80458    58496.0 -0.769923  1.692726  1.040596  2.314980  0.771871  1.194325   
283015  171312.0 -0.189767  0.110463  0.943858 -1.858640  0.021766 -1.061964   
52707    45598.0 -0.405662  0.993962  1.075721  0.447830  0.106284 -0.515013   
...          ...       ...       ...       ...       ...       ...       ...   
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494   
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536   
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346   
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548   
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695   

              V7        V8        V9  .

In [24]:
print(Y)

78406     0
123408    0
80458     0
283015    0
52707     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 946, dtype: int64


Splitting the data into training data and testing data

In [25]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [26]:
print(X.shape, X_train.shape, X_test.shape)

(946, 30) (756, 30) (190, 30)


Model Training

In [27]:
model1 = LogisticRegression()

In [28]:
model1.fit(X_train, Y_train)

LogisticRegression()

Model Evaluation

In [29]:
X_train_prediction = model1.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [30]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9470899470899471


In [31]:
X_test_prediction = model1.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [32]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9157894736842105


In [33]:
print('F1 score of the Logistic Regression model is: {}'.format(f1_score(X_test_prediction,Y_test)))

F1 score of the Logistic Regression model is: 0.9157894736842105


In [34]:
confusion_matrix(Y_test, X_test_prediction, labels = [0, 1])

array([[87,  8],
       [ 8, 87]], dtype=int64)

In [35]:
model2=DecisionTreeClassifier()

In [36]:
model2.fit(X_train, Y_train)

DecisionTreeClassifier()

In [37]:
X_train_prediction = model2.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [38]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  1.0


In [39]:
X_test_prediction = model2.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [40]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9105263157894737


In [41]:
print('F1 score of the Decision Tree model is: {}'.format(f1_score(X_test_prediction,Y_test)))

F1 score of the Decision Tree model is: 0.91005291005291


In [42]:
confusion_matrix(Y_test, X_test_prediction, labels = [0, 1])

array([[87,  8],
       [ 9, 86]], dtype=int64)

In [43]:

model3=RandomForestClassifier()


In [44]:
model3.fit(X_train, Y_train)

RandomForestClassifier()

In [45]:
X_train_prediction = model3.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [46]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  1.0


In [47]:
X_test_prediction = model3.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [48]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9421052631578948


In [49]:
print('F1 score of the Random Forest model is: {}'.format(f1_score(X_test_prediction,Y_test)))

F1 score of the Random Forest model is: 0.9392265193370165


In [50]:
confusion_matrix(Y_test, X_test_prediction, labels = [0, 1])

array([[94,  1],
       [10, 85]], dtype=int64)

In [51]:
n=5
model4=KNeighborsClassifier(n_neighbors=5)

In [52]:
model4.fit(X_train,Y_train)

KNeighborsClassifier()

In [53]:
X_train_prediction = model4.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [54]:
print('Accuracy score on Training Data : ', training_data_accuracy)

Accuracy score on Training Data :  0.7645502645502645


In [55]:
X_test_prediction = model4.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [56]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.7105263157894737


In [57]:
print('F1 score of the KNN model is: {}'.format(f1_score(X_test_prediction,Y_test)))

F1 score of the KNN model is: 0.7150259067357513


In [58]:
confusion_matrix(Y_test, X_test_prediction, labels = [0, 1])

array([[66, 29],
       [26, 69]], dtype=int64)

In [59]:
n=7
model5=KNeighborsClassifier(n_neighbors=7)

In [60]:
model5.fit(X_train, Y_train)

KNeighborsClassifier(n_neighbors=7)

In [61]:
X_train_prediction = model5.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [62]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.7301587301587301


In [63]:
X_test_prediction = model5.predict(X_test)
test_data_accuracy = accuracy_score(Y_test,X_test_prediction)

In [64]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.7052631578947368


In [65]:
print('F1 score of the KNN model is: {}'.format(f1_score(X_test_prediction,Y_test)))

F1 score of the KNN model is: 0.7021276595744681


In [66]:
confusion_matrix(Y_test, X_test_prediction, labels = [0, 1])

array([[68, 27],
       [29, 66]], dtype=int64)

In [67]:
model6=SVC()

In [68]:
model6.fit(X_train, Y_train)

SVC()

In [69]:
X_train_prediction = model6.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [70]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.5357142857142857


In [71]:
X_test_prediction = model6.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)


In [72]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.5526315789473685


In [73]:
print('F1 score of the SVM model is: {}'.format(f1_score(X_test_prediction,Y_test)))

F1 score of the SVM model is: 0.5641025641025641


In [74]:
confusion_matrix(Y_test, X_test_prediction, labels = [0, 1])

array([[50, 45],
       [40, 55]], dtype=int64)

Building a predictive model

In [75]:
input_data=(0,1.191857111,0.266150712,0.166480113,0.448154078,0.060017649,-0.082360809,-0.078802983,0.085101655,-0.255425128,-0.166974414,1.612726661,1.065235311,0.489095016,-0.143772296,0.635558093,0.463917041,-0.114804663,-0.18336127,-0.145783041,-0.069083135,-0.225775248,-0.638671953,0.101288021,-0.339846476,0.167170404,0.125894532,-0.008983099,0.014724169,2.69)

#change the input data to a numpy array
input_data_as_numpy_array=np.asarray(input_data)
#reshape the numpy array as we are predicting for only one instance
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
prediction=model3.predict(input_data_reshaped)
print(prediction)
if(prediction[0]==0):
    print('Normal transaction')
else:
    print('Fraudulent transaction')

[0]
Normal transaction


In [76]:
input_data=(472,-3.043540624,-3.157307121,1.08846278,2.288643618,1.35980513,-1.064822523,0.325574266,-0.067793653,-0.270952836,-0.838586565,-0.414575448,-0.50314086,0.676501545,-1.692028933,2.000634839,0.666779696,0.599717414,1.725321007,0.28334483,2.102338793,0.661695925,0.435477209,1.375965743,-0.293803153,0.279798032,-0.145361715,-0.252773123,0.035764225,529)
#change the input data to a numpy array
input_data_as_numpy_array=np.asarray(input_data)
#reshape the numpy array as we are predicting for only one instance
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
prediction=model3.predict(input_data_reshaped)
print(prediction)
if(prediction[0]==0):
    print('Normal transaction')
else:
    print('Fraudulent transaction')

[1]
Fraudulent transaction
